[project]
name = "basilisp-tools"
description = "Development tooling for Basilisp (initial scaffold)"
version = "0.0.1"
dependencies = [
  "basilisp[pytest]",
]
requires-python = ">=3.10"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
  "Development Status :: 1 - Planning",
  # "Programming Language :: Basilisp",
  "Programming Language :: Python",
]

[project.urls]
Homepage = "https://github.com/cospectrum/basilisp-tools"

[project.scripts]
basilisp-tools = "basilisp_tools.core:main"

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"*" = ["*.lpy"]
